### PR TITLE
OC-16858 Attribute autoqueries to system user

### PR DESCRIPTION
**Pull request by theywa**
#736

### CODE REVIEW

**Review by MartijnR — APPROVED** [review]
brilliant! :)

**Comment by MartijnR** [comment]
restarted CI testing

**Comment by MartijnR** [comment]
Are tests passing for you locally @theywa?

**Comment by theywa** [comment]
@MartijnR ~ I did, but the headless keeps failing before it is finished.  But now I tried again after seeing your comment, it looks like the test failed so I just updated the code. I'm sorry for the inconvenience.

**Comment by MartijnR** [comment]
ah yes, so there were tests for it! Thx.

**Pull request merged**
