### PR TITLE
IE support for enketo

### PR DESCRIPTION
**Pull request by rooney**
IE11 and IE10

### CODE REVIEW

**Comment by MartijnR** [comment]
@kkrumlian @rooney 

If you are using Enketo to edit draft records or already-submitted records, this also won't work in IE. This probably never worked but was only recently discovered. Sorry, I forgot to mention that during our last meeting.

Let me know if, despite this, you want me to review this or would like to first do this in-house. These 7 contexts would need to be checked: https://github.com/enketo/enketo-core#notes-for-css-developers.

I would also recommend adding this to the latest kobotoolbox/enketo-express master instead.

**Comment by MartijnR** [comment]
I like the approach of using browser-sniffing in this particular case.

**Comment by kkrumlian** [comment]
Hey Martijn,

Yes i would like you to still review the approach highlighted by @theywa. When we talk on monday let's discuss IE.x problems in general and get some time estimates for fixes.

**Comment by MartijnR** [comment]
Ok, will do. Do note, that I think there is a significant chance that I cannot get offline-capable forms and editing to work in IE.

**Comment by MartijnR** [comment]
I ran into a few problems (and then stopped reviewing further). Note that I reviewed this in the latest kobotoolbox/enketo-express for efficiency sake.

1. The reason `.main .paper` has `display: flex` is to push pages to full page height. This is important for e.g. forms in pages mode, or for very short forms in default (full-form) mode.

screen shot 2016-02-05 at 3 30 13 pm

2. The screen size responsiveness seems to be broken (maybe only in non-pages mode?)

screen shot 2016-02-05 at 3 16 12 pm

3. Sidebar in offline-capable webform view not stretching to bottom

screen shot 2016-02-05 at 3 14 58 pm

4. IE-specific file should probably target IE only. This can be done with a @media query, though I haven't checked if this also targets MS Edge, which would be undesirable. I fixed this. See link later on.

5. Re-organized files a bit, since the IE-specific css file is not specific to the OC theme only but to all themes. See link later on.

6. The fix for the "powered by" text was interfering with a fix upstream. Removed in link later on.

In order to try to fix the IE styling, I recommend working on a kobotoolbox/enketo-express port, and using this as the basis: https://github.com/kobotoolbox/enketo-express/compare/fix/IE11-styling?expand=1. 

Check the following:
1. very short 1 question form, not in pages mode
2. long form, not in pages mode
3. different screensizes
2. add ?touch=true to simulate touchscreen
3. print style
4. form in pages mode
5. form in OC theme
6. form in Grid theme
7. combinations of these

**Comment by rooney** [comment]
@MartijnR @kkrumlian 
Martijn's feedbacks have been addressed in bc3483d1aadd329831b77a19ecd97453c99cf03a

**Comment by rooney** [comment]
Also, video demoing that the feedbacks have been implemented: https://dl.dropboxusercontent.com/u/2606784/OC/Enketo-IE-Feedback.ogv

**Comment by MartijnR** [comment]
A few questions:

- So nothing has changed since [this branch](https://github.com/kobotoolbox/enketo-express/compare/fix/IE11-styling?expand=1)?  
- Does that mean that you couldn't reproduce any of the issues I found (1, 2, and 3)? 
- Did you test this from the latest enketo-express-oc master (or kobotoolbox/enketo-express)? 
- Did you perhaps check if the media query solution that I proposed is targeting MS Edge as well? That would be undesirable.

**Comment by MartijnR** [comment]
replaced by https://github.com/OpenClinica/enketo-express-oc/pull/24

**Pull request closed without merging**
