### PR TITLE
OC-6769 cssfix, reduce white space in form header

### PR DESCRIPTION
**Pull request by rooney**
Enketo could benefit from having less whitespace at the top of its forms.

https://jira.openclinica.com/browse/OC-6769

### CODE REVIEW

**Comment by MartijnR** [comment]
Thanks. Just checking: Was this tested with multi-language forms on very small screens?

**Comment by MartijnR** [comment]
And after actually looking at the code (sorry), do form logos (i.e. uploading a file called 'form_logo.png' as done [here](https://enke.to/::widgets) not need to be supported?

**Comment by dozymoe** [comment]
here a patch that goes to enketo-transformer https://gist.github.com/dozymoe/b8fbbb2a7f5327f80c9bbdd8edc38e95

if there is no form-logos make the section display:none

**Comment by MartijnR** [comment]
Thanks @dozymoe. If there is no form logo, the `<section class="form-logo">` element will be empty and have height 0 in my testing (also with the OC theme). 

screen shot 2016-04-15 at 7 54 24 am

Are you experiencing a layout issue? Does the DOM look like the one in the screenshot without an `` element inside the `<section>`?

**Comment by dozymoe** [comment]
There is white-space problem in mobile view, see screenshot.

The issue was about having too much white-space on the form-header, it's not clear how much, so my thought was removing excess white-space and wait for feedback.

I think it's safer to display:none the section.form-logo, even if it doesn't have child elements it's still not empty, or cannot be targeted with css selector `:empty`, there was spaces in between opening and closing tags. Or set default class to "hidden" and remove the class if there is custom form logo.

oc-6769-form-logo

**Comment by MartijnR** [comment]
Ah yes, thanks. It is this rule that is responsible for it:

```css
@media screen and (max-width: 820px)
  .or .form-logo {
      margin-top: 45px; 
  }
```

This rule serves a purpose, but we can move this margin to the `` element instead. I will do that. Thanks!

**Comment by MartijnR** [comment]
Done. Will be merged in next major merge (let me know if urgent).

**Pull request closed without merging**
