### PR TITLE
Participate IE11 errors on EDIT(remove re-direct on IE)

### PR DESCRIPTION
**Pull request by rooney**
https://jira.openclinica.com/browse/OC-7124

### CODE REVIEW

**Comment by MartijnR** [comment]
In my understanding editing an existing record is completely broken in IE. Hence the redirect. No so?

**Comment by rooney** [comment]
@MartijnR OK then

The redirect has been restored and now only the error message updated for clarity.

Let me know if it's good now or if you have other tought?

**Comment by MartijnR** [comment]
I'd prefer to keep it as is, for 2 reasons:

1. I am very reluctant to add new strings (or change existing strings) unless really really necessary/valuable. We have volunteers for about 20 languages now, and it's hard to get people to update translations. I want to stick to changing/adding strings only when really necessary to not discourage them. 
1. IE is on its way out, so this seems too much customization just for those few IE users. Plus the current message is not incorrect.

If you really want this customization in the OC EE port, then I recommend adding the strings to the jade template instead. This will make merging much easier (and I assume that OC, doesn't want to duplicate translations, and except that this will only be in English).

**Comment by kkrumlian** [comment]
Hey @MartijnR, 

Can we make a list of what is exactly broken so we can fix it? 

Thank you
Krikor

**Comment by MartijnR** [comment]
The only thing I'm aware of is that merging any record (draft record, or submitted-record-to-edit) fails with an exception on IE11. That would be the one to fix. 

It's only been described here: https://github.com/kobotoolbox/enketo-express/issues/352, and probably occurs in the mergeXML library: https://github.com/hareko/js-merge-xml

**Comment by MartijnR** [comment]
underlying issue fixed

**Pull request closed without merging**
