### PR TITLE
OC 6708

### PR DESCRIPTION
**Pull request by rooney**
changes needed on enketo side for OC-6708 (custom logo) to work

### CODE REVIEW

**Comment by rooney** [comment]
Hi @MartijnR 
So it seems that you don't like my approach to do custom logo.
How should I do it?

**Comment by MartijnR** [comment]
Oops, I don't know how this got closed! Sorry! 

(I don't even have the automatic authority and responsibility to review, close, merge PRs.)

**Comment by MartijnR** [comment]
FWIW, the code looks good. I would not add a custom logo via a webform URL query string though. I'd do it via the accounts API, but I don't know the requirements (OC-6708), and haven't been asked to review, so I probably shouldn't even be writing this. :)

**Comment by rooney** [comment]
@MartijnR thanks for the quick response
@kkrumlian said he'll setup a meeting for us to discuss about this.
Thanks

**Comment by MartijnR** [comment]
Great. After thinking some more about this, I wonder if you could just use this 1-line-function: https://github.com/kobotoolbox/enketo-express/blob/master/app/controllers/transformation-controller.js#L169-L171

The media controller can then proxy the logo request (from any domain). We could expand the function (and move it to utils.js) by adding the security check that you included in this PR.

**Comment by MartijnR** [comment]
This approach will cause the offline-capable forms to break. However, good news, the latest kobotoolbox/enketo-express has the code to add custom logos (l'm using this for Enketo's paid service at accounts.enketo.org). Client code here: https://github.com/kobotoolbox/enketo-express/blob/master/public/js/src/main-webform.js#L112-L128

**Pull request closed without merging**
